"""bookings Created_at

Revision ID: e6700e527719
Revises: 50d2a18b5259
Create Date: 2022-05-23 13:20:12.405203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6700e527719'
down_revision = '50d2a18b5259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
