name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    environment:
      name: uu81_fastapi
    env:
      DATABASE_HOSTNAME: localhostbhiublub;obouibub[bu9bjb;ihlijbhbihyb]
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Ifeanyi058
      DATABASE_NAME: UU815485456149837565141315874875147248475185475478185
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.DATABASE_SECRET_KEY}}
      ALGORITHM: ${{secrets.DATABASE_ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      PAYSTACK_SECRET_KEY: ${{secrets.DATABASE_PAYSTACK_SECRET_KEY}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_FROM: ${{secrets.MAIL_FROM}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_SERVER: ${{secrets.MAIL_SERVER}}
      MAIL_TLS: ${{secrets.MAIL_TLS}}
      MAIL_SSL: ${{secrets.MAIL_SSL}}
      USE_CREDENTIALS: ${{secrets.USE_CREDENTIALS}}
      VALIDATE_CERTS: ${{secrets.VALIDATE_CERTS}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_HOSTNAME}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo  
        uses: actions/checkout@v3
      - name: pip install python version 3.9
        uses: actions/setup-python@v3
        with:
          python version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest 