name: Build and Deploy Code

on: [push, pull_request]

jobs:
  GOD_ABEG:
    environment:
      name: uu81_fastapi
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      PAYSTACK_SECRET_KEY: ${{secrets.DATABASE_PAYSTACK_SECRET_KEY}}
      MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
      MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
      MAIL_FROM: ${{secrets.MAIL_FROM}}
      MAIL_PORT: ${{secrets.MAIL_PORT}}
      MAIL_SERVER: ${{secrets.MAIL_SERVER}}
      MAIL_FROM_NAME: ${{secrets.MAIL_FROM_NAME}}
      MAIL_TLS: ${{secrets.MAIL_TLS}}
      MAIL_SSL: ${{secrets.MAIL_SSL}}
      USE_CREDENTIALS: ${{secrets.USE_CREDENTIALS}}
      VALIDATE_CERTS: ${{secrets.VALIDATE_CERTS}}
      CLOUD_NAME: ${{secrets.CLOUD_NAME}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo  
        uses: actions/checkout@v2
      - name: pip install python version 3.9
        uses: actions/setup-python@v2
        with:
          python version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest 

  deploy:
    runs-on: ubuntu-latest
    needs: [GOD_ABEG]
    environment:
      name: production_uu81

    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: deploying to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}